### PR TITLE
fixed some deprecated methods

### PR DESCRIPTION
**Pull request by austinaryain**
Hey Mike, 

I heard about this project on Fragmented and was looking through it when I noticed some deprecated methods. I swapped them out with what I've found to be the successors.  

I'm fairly new at Android and Git so if I've missed something please let me know. 

Thanks

### CODE REVIEW

**Comment by mwolfson** [comment]
Thanks a bunch, I was planning on updating this project soon (to add all the fun stuff they just released).  I am sure I will accept this request, but just need to find the time to review it and stuff.

Totally appreciate the code help!

**Comment by mwolfson** [comment]
Need to get that CI working (It was never working, this build didn't work before).  Cheers, and thanks again.

**Comment by austinaryain** [comment]
I won't lie, I saw the build fail and went into a little bit of a panic mode thinking I submitted something broken!  I tried searching it up like crazy, but couldn't seem to get it working even locally.  From what I found it is something to do with a git ignore on the /gradle/wrapper/gradle-wrapper.jar. 

[This StackOverflow might be a help](http://stackoverflow.com/questions/29805622/could-not-find-or-load-main-class-org-gradle-wrapper-gradlewrappermain
)

**Comment by mwolfson** [comment]
Ha, I probably should disable that.  I haven't been working on this project much (and was playing with Circle here, in anticipation of a work project).

I generally polish the project in advance of me presenting on this topic, which I will be doing in Apr, so will be spending a bit of time to get this updated.

Once again appreciate your commit (sorry to freak you out, ;-) ).

**Pull request merged**
